language: java
jdk:
  - openjdk13
dist: bionic
services:
  - xvfb
before_install:
  - export DISPLAY=:99.0
#script: mvn test -B -Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k